-- =========================================================
-- SmartCode - per-problem Python syntax cheatsheets
-- Auto-generated by backend/scripts/generate_cheatsheets.py
-- Safe to re-run; idempotent UPDATE per row.
-- =========================================================

USE ai_tutor_system;

-- #1 two-sum
UPDATE problems SET cheatsheet_md = '## Dictionary (Hash Map)
```python
hash_map = {} # Create a new dictionary
hash_map[key] = value # Add or update an entry
value = hash_map[key] # Access a value
if key in hash_map: # Check if key exists
    pass
```' WHERE problem_id = 1;

-- #2 valid-parentheses
UPDATE problems SET cheatsheet_md = '## Stack
```python
stack = []               # Initialize an empty list as a stack
stack.append(item)       # Push an item onto the stack
item = stack.pop()       # Pop an item from the stack
is_empty = not stack     # Check if stack is empty
top_item = stack[-1]     # Peek at the top item
```

## Dictionary
```python
mapping = {'')'': ''('', ''}'': ''{'', '']'': ''[''} # Map closing to opening brackets
opening_bracket = mapping[char]          # Access value by key
is_key = char in mapping                 # Check if key exists
```

## Iteration
```python
for char in s:           # Iterate through string characters
    pass
```

## Conditional
```python
if condition:            # Basic if statement
    pass
elif other_condition:    # Optional elif
    pass
else:                    # Optional else
    pass
```

## Return
```python
return True              # Return boolean True
return False             # Return boolean False
```' WHERE problem_id = 2;

-- #3 reverse-linked-list
UPDATE problems SET cheatsheet_md = '## Linked List Node
```python
node = ListNode(val=0, next=None) # Create a new node
node.val = 10                     # Access node value
node.next = next_node             # Access next node reference
```

## Iteration
```python
current = head                    # Start at the head
while current:                    # Loop until current is None
    # do something with current
    current = current.next        # Move to the next node
```

## Reversing Pointers
```python
prev = None                       # Initialize previous node
current = head                    # Initialize current node
temp = current.next               # Store next node temporarily
current.next = prev               # Reverse current node''s pointer
prev = current                    # Move prev to current node
current = temp                    # Move current to next node
```' WHERE problem_id = 3;

-- #4 climbing-stairs
UPDATE problems SET cheatsheet_md = '## Base Cases
```python
if n == 1: return 1
if n == 2: return 2
```

## Dynamic Programming Array
```python
dp = [0] * (n + 1)
dp[1] = 1
dp[2] = 2
```

## Iteration
```python
for i in range(3, n + 1):
    dp[i] = dp[i-1] + dp[i-2]
```

## Return Value
```python
return dp[n]
```' WHERE problem_id = 4;

-- #5 best-time-to-buy-and-sell-stock
UPDATE problems SET cheatsheet_md = '## Variables
```python
max_profit = 0
min_price = float(''inf'') # Initialize with a very large number
```

## Iteration
```python
for price in prices:
    # Loop through each element
```

## Conditionals
```python
if current_profit > max_profit:
    max_profit = current_profit
```

## Math
```python
min_price = min(min_price, price) # Find the minimum of two values
current_profit = price - min_price # Calculate difference
```' WHERE problem_id = 5;

-- #6 maximum-subarray
UPDATE problems SET cheatsheet_md = '## Variables
```python
current_sum = 0
max_so_far = float(''-inf'') # Initialize with negative infinity
```

## Iteration
```python
for num in nums:
    # Process each number
```

## Math
```python
current_sum = max(num, current_sum + num) # Kadane''s algorithm core
max_so_far = max(max_so_far, current_sum)
```' WHERE problem_id = 6;

-- #7 container-with-most-water
UPDATE problems SET cheatsheet_md = '## Two Pointers
```python
left = 0
right = len(height) - 1
```

## Loop
```python
while left < right:
    # ...
    left += 1
    right -= 1
```

## Calculate Area
```python
current_height = min(height[left], height[right])
width = right - left
current_area = current_height * width
```

## Max Value
```python
max_area = 0
max_area = max(max_area, current_area)
```

## Conditional Pointer Movement
```python
if height[left] < height[right]:
    left += 1
else:
    right -= 1
```' WHERE problem_id = 7;

-- #8 three-sum
UPDATE problems SET cheatsheet_md = '## Sorting
```python
nums.sort() # in-place sort
```

## List operations
```python
result = []
result.append([a, b, c])
```

## Two pointers
```python
left = i + 1
right = len(nums) - 1
while left < right:
    # ...
    left += 1
    right -= 1
```

## Skipping duplicates
```python
while left < right and nums[left] == nums[left - 1]: # for left pointer
    left += 1
while left < right and nums[right] == nums[right + 1]: # for right pointer
    right -= 1
while i < len(nums) - 1 and nums[i] == nums[i+1]: # for outer loop
    i += 1
```

## Range and enumeration
```python
for i in range(len(nums)):
    # ...
```' WHERE problem_id = 8;

-- #9 group-anagrams
UPDATE problems SET cheatsheet_md = '## Dictionary
```python
d = {} # empty dictionary
d[key] = value
value = d[key]
if key in d:
    pass
```

## List Append
```python
my_list = []
my_list.append(item)
```

## String Operations
```python
s = "hello"
sorted_chars = sorted(s) # returns a list of chars
sorted_s = "".join(sorted_chars) # join list of chars to string
```' WHERE problem_id = 9;

-- #10 number-of-islands
UPDATE problems SET cheatsheet_md = '## Grid dimensions
```python
rows = len(grid)
cols = len(grid[0])
```

## Iterating grid
```python
for r in range(rows):
    for c in range(cols):
        # Access grid[r][c]
```

## DFS traversal
```python
def dfs(r, c):
    if r < 0 or r >= rows or c < 0 or c >= cols or grid[r][c] == ''0'':
        return
    grid[r][c] = ''0'' # Mark as visited
    dfs(r + 1, c)
    dfs(r - 1, c)
    dfs(r, c + 1)
    dfs(r, c - 1)
```

## BFS traversal
```python
from collections import deque
q = deque()
q.append((r, c))
grid[r][c] = ''0'' # Mark as visited
while q:
    curr_r, curr_c = q.popleft()
    for dr, dc in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
        nr, nc = curr_r + dr, curr_c + dc
        if 0 <= nr < rows and 0 <= nc < cols and grid[nr][nc] == ''1'':
            grid[nr][nc] = ''0'' # Mark as visited
            q.append((nr, nc))
```' WHERE problem_id = 10;

-- #11 coin-change
UPDATE problems SET cheatsheet_md = '## DP Array Initialization
```python
dp = [float(''inf'')] * (amount + 1)
dp[0] = 0
```

## Iterating
```python
for i in range(1, amount + 1):
    for coin in coins:
        if i - coin >= 0:
            dp[i] = min(dp[i], 1 + dp[i - coin])
```

## Return Value
```python
if dp[amount] == float(''inf''):
    return -1
return dp[amount]
```' WHERE problem_id = 11;

-- #12 longest-substring-without-repeating-characters
UPDATE problems SET cheatsheet_md = '## Sliding Window
```python
left = 0
right = 0
max_length = 0
while right < len(s):
    # expand window
    right += 1
# shrink window
left += 1
```

## Hash Set
```python
char_set = set()
char_set.add(char)
char_set.remove(char)
if char in char_set:
    pass
```

## String Length
```python
n = len(s)
```

## Max Value
```python
max_val = max(max_val, current_val)
```' WHERE problem_id = 12;

-- #13 trapping-rain-water
UPDATE problems SET cheatsheet_md = '## Array iteration
```python
n = len(height)
for i in range(n): # forward
    _ = height[i]
for i in range(n - 1, -1, -1): # backward
    _ = height[i]
```

## Two pointers
```python
left, right = 0, n - 1
while left < right:
    left_val = height[left]
    right_val = height[right]
    # move pointers
    if left_val < right_val:
        left += 1
    else:
        right -= 1
```

## Max tracking
```python
current_max = 0
current_max = max(current_max, new_value)
```

## Variable assignment
```python
total_water = 0
total_water += water_at_index
```' WHERE problem_id = 13;

-- #14 word-ladder
UPDATE problems SET cheatsheet_md = '## Queue (BFS)
```python
from collections import deque

q = deque()
q.append((beginWord, 1)) # (word, level)
word, level = q.popleft()
```

## Set
```python
wordList = set(wordList)
if endWord not in wordList: # check existence
    return 0
visited = set()
visited.add(beginWord)
```

## String Iteration
```python
word_list = list(word) # convert to list for mutability
for i in range(len(word_list)):
    original_char = word_list[i]
    for char_code in range(ord(''a''), ord(''z'') + 1):
        word_list[i] = chr(char_code)
    word_list[i] = original_char # backtrack
new_word = "".join(word_list)
```' WHERE problem_id = 14;

-- #15 median-of-two-sorted-arrays
UPDATE problems SET cheatsheet_md = '## Array Length
```python
m = len(nums1)
n = len(nums2)
total_length = m + n
```

## Integer Division
```python
mid_index = total_length // 2
```

## Binary Search
```python
left, right = 0, len(arr) - 1
while left <= right:
    mid = (left + right) // 2
    # ... comparison logic ...
    left = mid + 1
    right = mid - 1
```

## Accessing Elements
```python
element = nums[i]
```

## Edge Cases (Min/Max Values)
```python
import math
max_val = math.inf
min_val = -math.inf
```' WHERE problem_id = 15;

-- #16 contains-duplicate
UPDATE problems SET cheatsheet_md = '## Set
```python
my_set = set()
my_set.add(element)
if element in my_set: pass
```

## List to Set Conversion
```python
my_list = [1, 2, 2, 3]
unique_elements = set(my_list)
```

## Length
```python
list_len = len(my_list)
set_len = len(my_set)
```' WHERE problem_id = 16;

-- #17 valid-anagram
UPDATE problems SET cheatsheet_md = '## Dictionary (Hash Map)
```python
counts = {} # Initialize empty dictionary
counts[char] = counts.get(char, 0) + 1 # Increment count
counts[char] = counts.get(char, 0) - 1 # Decrement count
if char in counts: # Check if key exists
    pass
if not counts[char]: # Check if count is zero (falsy)
    del counts[char] # Remove key if count is zero
```

## Collections Counter
```python
from collections import Counter
counts_s = Counter(s) # Create Counter from string
counts_t = Counter(t) # Create Counter from string
if counts_s == counts_t: # Compare two Counter objects
    pass
```

## String Length
```python
length_s = len(s) # Get length of string s
length_t = len(t) # Get length of string t
```

## Conditional
```python
if condition: # Basic if statement
    pass
else: # Else block
    pass
```' WHERE problem_id = 17;

-- #18 fizz-buzz
UPDATE problems SET cheatsheet_md = '## List Initialization
```python
result = [None] * n
result = []
```

## Looping
```python
for i in range(1, n + 1):
    # i will be 1, 2, ..., n
```

## Modulo Operator
```python
is_divisible_by_3 = (i % 3 == 0)
is_divisible_by_5 = (i % 5 == 0)
```

## String Conversion
```python
s = str(i)
```

## List Assignment
```python
result[i-1] = "FizzBuzz"
result.append("Fizz")
```' WHERE problem_id = 18;

-- #19 plus-one
UPDATE problems SET cheatsheet_md = '## List Iteration
```python
for i in range(len(digits) - 1, -1, -1): # Iterate backwards
    digit = digits[i]
```

## List Modification
```python
digits[i] = new_value
digits.append(new_value)
digits.insert(0, new_value) # Insert at beginning
```

## List Creation
```python
new_list = [0] * (n + 1) # Create list of n+1 zeros
result = [1] + digits # Prepend an element
```' WHERE problem_id = 19;

-- #20 single-number
UPDATE problems SET cheatsheet_md = '## XOR Properties
```python
0 ^ x == x
x ^ x == 0
a ^ b ^ a == b # Commutative and associative
```

## Iterating List
```python
for num in nums:
    # process num
```

## Return Value
```python
return result
```' WHERE problem_id = 20;

-- #21 missing-number
UPDATE problems SET cheatsheet_md = '## Summation
```python
n = len(nums)
expected_sum = n * (n + 1) // 2
actual_sum = sum(nums)
missing = expected_sum - actual_sum
```

## Set Operations
```python
n = len(nums)
num_set = set(nums)
for i in range(n + 1):
    if i not in num_set:
        return i
```

## XOR
```python
n = len(nums)
missing = n # Initialize with n, as it''s a potential missing number
for i, num in enumerate(nums):
    missing ^= i
    missing ^= num
```' WHERE problem_id = 21;

-- #22 palindrome-number
UPDATE problems SET cheatsheet_md = '## Integer to String
```python
s = str(x)
```

## String Reversal
```python
reversed_s = s[::-1]
```

## String Comparison
```python
if s == reversed_s:
    # ...
```

## Edge Cases
```python
if x < 0:
    return False
```' WHERE problem_id = 22;

-- #23 reverse-integer
UPDATE problems SET cheatsheet_md = '## Integer properties
```python
INT_MAX = 2**31 - 1
INT_MIN = -2**31
```

## Modulo and division
```python
digit = x % 10 # Get last digit
x //= 10       # Integer division
x = abs(x)     # Absolute value
```

## Building reversed number
```python
rev = 0
rev = rev * 10 + digit
```

## Conditional logic
```python
if x < 0:
    # Handle negative sign
    pass
if rev > INT_MAX or rev < INT_MIN:
    return 0 # Overflow check
```' WHERE problem_id = 23;

-- #24 roman-to-integer
UPDATE problems SET cheatsheet_md = '## Dictionary
```python
roman_map = {''I'': 1, ''V'': 5, ''X'': 10, ''L'': 50, ''C'': 100, ''D'': 500, ''M'': 1000}
value = roman_map[''I''] # Access value by key
```

## String Iteration
```python
for i in range(len(s)):
    char = s[i]
for i in range(len(s) - 1): # Iterate up to second to last
    pass
```

## Conditional Logic
```python
if condition:
    pass
elif other_condition:
    pass
else:
    pass
```

## Integer Arithmetic
```python
total = 0
total += 1 # Add to total
total -= 1 # Subtract from total
```' WHERE problem_id = 24;

-- #25 majority-element
UPDATE problems SET cheatsheet_md = '## Dictionary (Hash Map)
```python
counts = {}
counts[num] = counts.get(num, 0) + 1 # Increment count
if counts[num] > len(nums) // 2:
    return num
```

## Sorting
```python
nums.sort()
return nums[len(nums) // 2]
```

## Boyer-Moore Voting Algorithm
```python
candidate = 0
count = 0
for num in nums:
    if count == 0:
        candidate = num
    count += (1 if num == candidate else -1)
return candidate
```' WHERE problem_id = 25;

-- #26 move-zeroes
UPDATE problems SET cheatsheet_md = '## List Iteration
```python
for x in nums:
    pass # iterate by value
for i in range(len(nums)):
    x = nums[i] # iterate by index
```

## In-place Modification
```python
nums[i] = val # assign value at index
nums.append(x) # add to end
nums.pop() # remove from end
```

## Two Pointers
```python
left = 0
right = 0
while right < len(nums):
    # logic with left and right
    right += 1
```

## Swapping Elements
```python
nums[i], nums[j] = nums[j], nums[i] # swap values
```' WHERE problem_id = 26;

-- #27 happy-number
UPDATE problems SET cheatsheet_md = '## Number to Digits
```python
str_n = str(n)               # Convert number to string
digit = int(char)            # Convert character digit back to int
```

## Sum of Squares
```python
total_sum = 0
total_sum += digit * digit   # Add square of digit
```

## Set for Cycle Detection
```python
seen = set()
if n in seen:                # Check if number seen before
    return False
seen.add(n)                  # Add number to set
```

## Loop Control
```python
while n != 1 and n not in seen: # Loop until 1 or cycle detected
    # ... calculations ...
return n == 1                # Check final condition
```' WHERE problem_id = 27;

-- #28 power-of-two
UPDATE problems SET cheatsheet_md = '## Integer properties
```python
n > 0 # Check if positive
n & (n - 1) == 0 # Check if power of two using bitwise AND
```' WHERE problem_id = 28;

-- #29 excel-sheet-column-number
UPDATE problems SET cheatsheet_md = '## String iteration
```python
for char in s:
    # process char
for i in range(len(s)):
    char = s[i]
```

## Character to integer
```python
ord(''A'') # ASCII value of ''A''
ord(''Z'') - ord(''A'') + 1 # 26
```

## Arithmetic
```python
result = 0
result = result * 26 + digit # base 26 conversion
```' WHERE problem_id = 29;

-- #30 length-of-last-word
UPDATE problems SET cheatsheet_md = '## String methods
```python
s.strip() # Remove leading/trailing whitespace
s.split('' '') # Split by space into list of words
```

## List indexing
```python
my_list = [1, 2, 3]
last_element = my_list[-1]
```

## String length
```python
word = "hello"
length = len(word)
```' WHERE problem_id = 30;

-- #31 product-of-array-except-self
UPDATE problems SET cheatsheet_md = '## List Initialization
```python
n = len(nums)
answer = [1] * n
```

## Loop - Left Pass
```python
prefix_product = 1
for i in range(n):
    answer[i] = prefix_product
    prefix_product *= nums[i]
```

## Loop - Right Pass
```python
suffix_product = 1
for i in range(n - 1, -1, -1):
    answer[i] *= suffix_product
    suffix_product *= nums[i]
```' WHERE problem_id = 31;

-- #32 rotate-array
UPDATE problems SET cheatsheet_md = '## List Slicing
```python
n = len(nums)
k %= n
rotated_part = nums[n - k:] # elements from index n-k to end
remaining_part = nums[:n - k] # elements from start to index n-k-1
```

## List Concatenation
```python
nums[:] = rotated_part + remaining_part # assign new list to original slice
```

## In-place Reversal
```python
nums.reverse() # reverses the entire list in-place
nums[start:end] = nums[start:end][::-1] # reverses a sublist in-place
```' WHERE problem_id = 32;

-- #33 search-in-rotated-sorted-array
UPDATE problems SET cheatsheet_md = '## Binary Search Setup
```python
left, right = 0, len(nums) - 1
while left <= right:
    mid = (left + right) // 2
    if nums[mid] == target:
        return mid
```

## Adjusting Pointers
```python
if nums[mid] < target:
    left = mid + 1
else:
    right = mid - 1
```

## Checking Sorted Half
```python
if nums[left] <= nums[mid]: # Left half is sorted
    # Check if target is in left half
    if nums[left] <= target < nums[mid]:
        right = mid - 1
    else:
        left = mid + 1
else: # Right half is sorted
    # Check if target is in right half
    if nums[mid] < target <= nums[right]:
        left = mid + 1
    else:
        right = mid - 1
```

## Return Not Found
```python
return -1
```' WHERE problem_id = 33;

-- #34 sort-colors
UPDATE problems SET cheatsheet_md = '## In-place modification
```python
nums[i], nums[j] = nums[j], nums[i] # Swap elements
```

## While loop
```python
while condition:
    # loop body
    i += 1
```

## List length
```python
n = len(nums)
```' WHERE problem_id = 34;

-- #35 rotate-image
UPDATE problems SET cheatsheet_md = '## In-place Swap
```python
matrix[r][c], matrix[c][r] = matrix[c][r], matrix[r][c] # Swap elements
```

## Reversing Rows
```python
row.reverse() # Reverse a list in-place
```

## Iterating Matrix
```python
for r in range(n):
    for c in range(r, n): # Iterate upper triangle (inclusive diagonal)
        pass
for r in range(n):
    for c in range(n // 2): # Iterate first half of columns
        pass
```' WHERE problem_id = 35;

-- #36 subsets
UPDATE problems SET cheatsheet_md = '## Backtracking
```python
res = []
path = []

def backtrack(start_index):
    res.append(list(path)) # Add a copy of the current path

    for i in range(start_index, len(nums)):
        path.append(nums[i])
        backtrack(i + 1) # Recurse with next element
        path.pop() # Backtrack
```

## List operations
```python
my_list = []
my_list.append(item)
my_list.pop()
copied_list = list(my_list) # Create a shallow copy
```

## Iteration
```python
for i in range(len(nums)):
    # ...
for i in range(start, end):
    # ...
```' WHERE problem_id = 36;

-- #37 combination-sum
UPDATE problems SET cheatsheet_md = '## Backtracking Function
```python
def backtrack(start_index, current_sum, current_combination):
    if current_sum == target:
        result.append(list(current_combination)) # Found a combination
        return
    if current_sum > target:
        return # Pruning: sum exceeds target

    for i in range(start_index, len(candidates)):
        num = candidates[i]
        current_combination.append(num)
        backtrack(i, current_sum + num, current_combination) # Recurse with current number
        current_combination.pop() # Backtrack
```

## List Initialization
```python
result = []
current_combination = []
```

## Function Call
```python
backtrack(0, 0, []) # (start_index, current_sum, current_combination)
return result
```' WHERE problem_id = 37;

-- #38 spiral-matrix
UPDATE problems SET cheatsheet_md = '## Matrix Dimensions
```python
rows = len(matrix)
cols = len(matrix[0])
```

## List Initialization
```python
result = []
```

## Loop Control
```python
while left <= right and top <= bottom:
    # ...
    top += 1
    bottom -= 1
    left += 1
    right -= 1
```

## Range Iteration
```python
for c in range(left, right + 1): # Traverse right
    result.append(matrix[top][c])
for r in range(top, bottom + 1): # Traverse down
    result.append(matrix[r][right])
for c in range(right, left - 1, -1): # Traverse left
    result.append(matrix[bottom][c])
for r in range(bottom, top - 1, -1): # Traverse up
    result.append(matrix[r][left])
```

## Conditional Check
```python
if top <= bottom: # Check for remaining rows
    # ...
if left <= right: # Check for remaining columns
    # ...
```' WHERE problem_id = 38;

-- #39 unique-paths
UPDATE problems SET cheatsheet_md = '## 2D Array / Grid
```python
grid = [[0] * n for _ in range(m)] # m rows, n columns
grid[r][c] = 1
```

## Dynamic Programming
```python
dp = {} # Dictionary for memoization
dp[(r, c)] = value
```

## Base Cases
```python
if r == m - 1 and c == n - 1: return 1
if r >= m or c >= n: return 0
```

## Recursion
```python
result = self.uniquePaths(r + 1, c) + self.uniquePaths(r, c + 1)
```' WHERE problem_id = 39;

-- #40 minimum-path-sum
UPDATE problems SET cheatsheet_md = '## Grid Dimensions
```python
rows = len(grid)
cols = len(grid[0])
```

## DP Table Initialization
```python
dp = [[0] * cols for _ in range(rows)]
dp[0][0] = grid[0][0]
```

## Iterating Grid
```python
for r in range(rows):
    for c in range(cols):
        # Access grid element
        val = grid[r][c]
```

## DP State Transitions
```python
dp[r][c] = grid[r][c] + min(dp[r-1][c], dp[r][c-1]) # From top or left
dp[r][c] = grid[r][c] + dp[r-1][c] # From top only
dp[r][c] = grid[r][c] + dp[r][c-1] # From left only
```

## Edge Cases (First Row/Column)
```python
if r > 0 and c == 0: # First column (not first row)
    dp[r][c] = grid[r][c] + dp[r-1][c]
if c > 0 and r == 0: # First row (not first column)
    dp[r][c] = grid[r][c] + dp[r][c-1]
```' WHERE problem_id = 40;

-- #41 jump-game
UPDATE problems SET cheatsheet_md = '## Array iteration
```python
n = len(nums)
for i in range(n):
    # Process nums[i]
for i in range(n - 1, -1, -1):
    # Iterate backwards
```

## Variable assignment
```python
max_reach = 0
last_index = n - 1
```

## Conditional logic
```python
if current_reach >= last_index:
    return True
if i > max_reach:
    return False
```

## Max function
```python
max_reach = max(max_reach, i + nums[i])
```' WHERE problem_id = 41;

-- #42 word-break
UPDATE problems SET cheatsheet_md = '## Dynamic Programming
```python
dp = [False] * (len(s) + 1)
dp[0] = True # Base case
for i in range(1, len(s) + 1):
    pass # Iterate through string segments
for j in range(i):
    pass # Iterate through previous states
dp[i] = dp[j] and (s[j:i] in word_set) # State transition
return dp[len(s)]
```

## String Slicing
```python
sub_string = s[j:i] # Slice from index j up to (but not including) i
len_s = len(s) # Length of the string
```

## Set Operations
```python
word_set = set(wordDict) # Convert list to set for O(1) average lookup
if word in word_set:
    pass # Check for membership
```' WHERE problem_id = 42;

-- #43 longest-increasing-subsequence
UPDATE problems SET cheatsheet_md = '## List Initialization
```python
dp = [1] * len(nums)
tails = []
```

## Iteration
```python
for num in nums:
for i in range(len(nums)):
for j in range(i):
```

## List Operations
```python
tails.append(num)
tails[idx] = num
len(tails)
```

## Conditional Logic
```python
if num > tails[-1]:
if nums[i] > nums[j]:
```

## Binary Search (bisect_left)
```python
import bisect
idx = bisect.bisect_left(tails, num) # find insertion point
```

## Max Value
```python
max_len = 0
max_len = max(max_len, dp[i])
```' WHERE problem_id = 43;

-- #44 house-robber
UPDATE problems SET cheatsheet_md = '## Base Cases
```python
if not nums: return 0
if len(nums) == 1: return nums[0]
```

## DP Array Initialization
```python
dp = [0] * len(nums)
dp[0] = nums[0]
dp[1] = max(nums[0], nums[1])
```

## DP Iteration
```python
for i in range(2, len(nums)):
    dp[i] = max(dp[i-1], nums[i] + dp[i-2])
```

## Return Value
```python
return dp[-1]
```' WHERE problem_id = 44;

-- #45 kth-largest-element-in-an-array
UPDATE problems SET cheatsheet_md = '## Min-Heap (Smallest k elements)
```python
import heapq

min_heap = []
heapq.heappush(min_heap, item)
smallest_item = heapq.heappop(min_heap)
heapq.heapreplace(min_heap, item) # pop then push
heapq.nsmallest(k, nums) # returns a list
```

## Max-Heap (Largest k elements)
```python
import heapq

max_heap = []
heapq.heappush(max_heap, -item) # negate for max-heap
largest_item = -heapq.heappop(max_heap) # negate back
```

## Sorting
```python
nums.sort() # in-place ascending
nums.sort(reverse=True) # in-place descending
sorted_nums = sorted(nums) # new list, ascending
kth_largest = nums[-k] # after ascending sort
```

## Quickselect (Partitioning)
```python
import random

pivot_index = random.randint(0, len(nums) - 1)
pivot = nums[pivot_index]
left = [x for x in nums if x < pivot]
mid = [x for x in nums if x == pivot]
right = [x for x in nums if x > pivot]
```' WHERE problem_id = 45;

-- #46 edit-distance
UPDATE problems SET cheatsheet_md = '## 2D DP Table
```python
dp = [[0] * (len(word2) + 1) for _ in range(len(word1) + 1)]
dp[i][j] = 0 # initialize cell
```

## Iteration
```python
for i in range(len(word1) + 1):
    pass
for j in range(len(word2) + 1):
    pass
```

## String Characters
```python
word1[i-1] # access character
```

## Min
```python
min(val1, val2, val3) # minimum of multiple values
```' WHERE problem_id = 46;

-- #47 first-missing-positive
UPDATE problems SET cheatsheet_md = '## Array / List Length
```python
n = len(nums)
```

## In-place Swap
```python
nums[i], nums[j] = nums[j], nums[i]
```

## Iteration
```python
for i in range(n):
for i, num in enumerate(nums):
```

## Conditional Logic
```python
if condition:
    pass
elif other_condition:
    pass
else:
    pass
```

## Return Value
```python
return 1
return i + 1
```' WHERE problem_id = 47;

-- #48 largest-rectangle-in-histogram
UPDATE problems SET cheatsheet_md = '## Stack
```python
stack = []
stack.append((index, height)) # Store (index, height)
index, height = stack.pop()
if not stack: # Check if stack is empty
    pass
```

## Loop and Range
```python
n = len(heights)
for i in range(n):
    pass
for i in range(n + 1): # Loop one extra time for final calculations
    pass
```

## Max Value
```python
max_area = 0
max_area = max(max_area, current_area)
```' WHERE problem_id = 48;

-- #49 n-queens-count
UPDATE problems SET cheatsheet_md = '## Backtracking
```python
def backtrack(row):
    if row == n:
        self.count += 1
        return

    for col in range(n):
        if is_safe(row, col):
            board[row][col] = ''Q''
            backtrack(row + 1)
            board[row][col] = ''.'' # backtrack
```

## Board Initialization
```python
board = [[''.'' for _ in range(n)] for _ in range(n)]
```

## Set Operations
```python
cols = set()
pos_diag = set() # r + c
neg_diag = set() # r - c

cols.add(c)
cols.remove(c)
if c in cols: pass
```' WHERE problem_id = 49;

-- #50 sliding-window-maximum
UPDATE problems SET cheatsheet_md = '## Deque (collections.deque)
```python
from collections import deque
d = deque()
d.append(x)
d.appendleft(x)
d.pop()
d.popleft()
x = d[0] # peek left
x = d[-1] # peek right
```

## List operations
```python
result = []
result.append(x)
```

## Loop and range
```python
n = len(nums)
for i in range(n):
for i in range(k - 1, n): # start index for window
```

## Conditional logic
```python
if condition:
    pass
while d and condition: # check if deque is not empty
    d.pop()
```' WHERE problem_id = 50;

-- #51 minimum-window-substring
UPDATE problems SET cheatsheet_md = '## Dictionary (Hash Map)
```python
char_counts = {} # Initialize
char_counts[char] = char_counts.get(char, 0) + 1 # Increment count
char_counts[char] -= 1 # Decrement count
if char_counts[char] == 0: # Check if count is zero
    del char_counts[char] # Remove entry
```

## String Slicing
```python
sub = s[left:right+1] # Inclusive slice
min_len = float(''inf'') # Initialize min length
result_str = "" # Initialize result string
```

## Two Pointers (Sliding Window)
```python
left = 0 # Left pointer
right = 0 # Right pointer
while right < len(s): # Expand window
    # ...
    while condition_met: # Shrink window
        # ...
        left += 1 # Move left pointer
    right += 1 # Move right pointer
```

## Character Ordinal Values
```python
ord(''a'') # Get ASCII/Unicode value
chr(97) # Convert value to character
```' WHERE problem_id = 51;

-- #52 burst-balloons
UPDATE problems SET cheatsheet_md = '## Array manipulation
```python
nums = [1] + nums + [1] # Add boundary balloons
n = len(nums) # Get length
```

## 2D DP Table
```python
dp = [[0] * n for _ in range(n)] # Initialize n x n table
dp[i][j] = value # Assign value
```

## Loops
```python
for length in range(2, n): # Iterate for length
for i in range(n - length): # Iterate for start index
j = i + length # Calculate end index
for k in range(i + 1, j): # Iterate for split point
```

## Max
```python
max_coins = max(max_coins, current_coins) # Update maximum
```' WHERE problem_id = 52;

-- #53 wildcard-matching
UPDATE problems SET cheatsheet_md = '## DP Table Initialization
```python
dp = [[False] * (len(p) + 1) for _ in range(len(s) + 1)]
dp[0][0] = True # Base case: empty string matches empty pattern
```

## DP State Transition (Character Match)
```python
if p[j-1] == s[i-1] or p[j-1] == ''?'':
    dp[i][j] = dp[i-1][j-1]
```

## DP State Transition (Wildcard ''*'')
```python
if p[j-1] == ''*'':
    dp[i][j] = dp[i-1][j] or dp[i][j-1] # ''*'' matches char or empty sequence
```

## Handling Initial ''*'' in Pattern
```python
for j in range(1, len(p) + 1):
    if p[j-1] == ''*'':
        dp[0][j] = dp[0][j-1] # ''*'' can match empty string
```

## Accessing DP Result
```python
return dp[len(s)][len(p)]
```' WHERE problem_id = 53;

-- #54 regular-expression-matching
UPDATE problems SET cheatsheet_md = '## Base Cases
```python
if not p: return not s
```

## Character Matching
```python
first_match = (bool(s) and p[0] in (s[0], ''.''))
```

## Star Quantifier (`*`)
```python
if len(p) >= 2 and p[1] == ''*'':
    # Case 1: ''*'' matches zero occurrences
    # Case 2: ''*'' matches one or more occurrences
    return self.isMatch(s, p[2:]) or \\
           (first_match and self.isMatch(s[1:], p))
```

## Standard Match
```python
return first_match and self.isMatch(s[1:], p[1:])
```

## Memoization (DP)
```python
memo = {} # Store results of (i, j)
if (i, j) in memo: return memo[(i, j)]
memo[(i, j)] = result # Store and return
```' WHERE problem_id = 54;

-- #55 longest-valid-parentheses
UPDATE problems SET cheatsheet_md = '## Stack
```python
stack = []
stack.append(item)
item = stack.pop()
is_empty = not stack
```

## String Iteration
```python
for char in s:
    # process char
for i in range(len(s)):
    char = s[i]
```

## Max Value
```python
max_length = 0
max_length = max(max_length, current_length)
```

## Conditional Logic
```python
if condition:
    # do something
elif other_condition:
    # do something else
else:
    # default action
```' WHERE problem_id = 55;

