"""
LLM-driven dynamic hint generator.

Hints are not pre-written templates anymore — each one is generated by the
LLM based on what the student has written SO FAR. Two students stuck on the
same problem get different hints if their code has different issues.

Three escalating levels:
  Level 1: a high-level nudge (data structure / general approach), without
           giving any code or naming the algorithm explicitly.
  Level 2: a more specific direction (algorithm category + key invariant
           the student is missing). Still no code.
  Level 3+: very concrete — describe the algorithm step by step, may
            mention 2-3 lines of pseudocode (not full solution).

The generator also has a heuristic fallback (canned text) so the editor
keeps working when the LLM is offline.
"""

from __future__ import annotations

import logging
from typing import Literal

from pydantic import BaseModel

from . import client as llm_client

log = logging.getLogger("ai_tutor.llm.hint_generator")


class HintInput(BaseModel):
    problem_title: str
    difficulty: Literal["easy", "medium", "hard"]
    statement_md: str
    constraints_md: str | None
    sample_cases: list[dict]   # [{name, input_blob, expected_blob}]
    user_code: str
    level: int                  # 1-based; >=3 caps to "level 3" content


class HintResult(BaseModel):
    hint_level: int
    hint_text_md: str
    source: Literal["llm", "heuristic"]


_SYSTEM_PROMPT = """You are a Socratic tutor for a Python programming class. The student is stuck on a problem and asked for a hint. You are shown their CURRENT code-in-progress and you must respond with a SHORT hint tailored to what they've written — not a generic one.

You will be given:
  - the problem statement and constraints
  - 1-2 sample test cases
  - the student's current code (which may be empty, a stub, or a partial / buggy attempt)
  - a `level` (1, 2, or 3) indicating how revealing the hint should be

Hint-by-level rules:
  - Level 1: A NUDGE. Point at the right family of approach in one sentence — never name the algorithm outright, never show code. Examples: "Think about what data structure gives you O(1) lookups." or "Try walking through the input from both ends."
  - Level 2: A DIRECTION. State the algorithmic idea explicitly (e.g. "Use a hash map keyed by complement", "Use Kadane's running max"). Describe the key invariant the student needs to maintain. Still no code.
  - Level 3: CONCRETE. Describe the algorithm step by step, may show 2-3 lines of pseudocode or a single line of Python (NOT the full solution). Aim to get the student unstuck without solving it for them.

Tailoring rules — this is the whole point of dynamic hints:
  - If the student's code is EMPTY or just the starter stub, give a getting-started hint at the requested level.
  - If the student's code references the right data structure but uses it wrong, point at the specific misuse.
  - If the student's code uses the wrong approach for the constraints (e.g. O(n^2) when constraints demand O(n log n)), call that out.
  - If the student's code is missing a base case / edge handling, mention it without giving the value.
  - If the student's code is mostly correct, congratulate them and point at the one bug.

DO NOT:
  - solve the problem outright (no full solution code, ever)
  - give more information than the requested level allows
  - mention the test cases by their literal input/output values

Respond with a single JSON object — no prose, no code fences:

{
  "hint_text_md": "your hint, 1-4 sentences max. May include a single 1-3 line code/pseudocode block inside backticks if and only if level == 3."
}"""


def generate_hint(inp: HintInput) -> HintResult:
    """Try the LLM; fall back to heuristic. Always returns something."""
    level = max(1, min(3, inp.level))
    if llm_client.is_available():
        try:
            return _generate_with_llm(inp, level)
        except Exception as exc:  # noqa: BLE001
            log.warning("LLM hint generation failed, using heuristic: %s", exc)
    return _generate_with_heuristic(inp, level)


# --------------------------- LLM path ---------------------------

def _generate_with_llm(inp: HintInput, level: int) -> HintResult:
    parts = [
        f"# Problem: {inp.problem_title} ({inp.difficulty})",
        f"## Statement\n{inp.statement_md}",
    ]
    if inp.constraints_md:
        parts.append(f"## Constraints\n{inp.constraints_md}")
    if inp.sample_cases:
        parts.append("## Sample cases (for grounding only — do NOT echo values back)")
        for c in inp.sample_cases[:2]:
            name = c.get("name") or ""
            parts.append(f"### {name}")
            parts.append(f"Input:\n```\n{c.get('input_blob', '')}\n```")
            parts.append(f"Expected:\n```\n{c.get('expected_blob', '')}\n```")
    code = (inp.user_code or "").strip()
    parts.append("## Student's current code")
    code_display = code if code else "(empty - the student has not typed anything yet)"
    parts.append(f"```python\n{code_display}\n```")
    parts.append(f"\nHint level requested: {level}")
    parts.append("Now produce the JSON hint object.")
    user_text = "\n\n".join(parts)

    raw = llm_client.call_json(system=_SYSTEM_PROMPT, user=user_text, max_tokens=512)
    text = str(raw.get("hint_text_md") or "").strip()
    if not text:
        raise ValueError("LLM returned empty hint")
    return HintResult(hint_level=level, hint_text_md=text, source="llm")


# --------------------------- Heuristic fallback ---------------------------

_FALLBACK_BY_LEVEL = {
    1: "Re-read the problem statement and walk through a small example by hand. What state would you need to track to produce the expected output in one pass?",
    2: "Identify the algorithmic pattern that fits the constraints (hash map, two pointers, sliding window, DP, BFS/DFS). Pick the simplest one consistent with the input size.",
    3: "Sketch the algorithm in pseudocode first: what's the initial state, the per-iteration update, and the final return value? Then translate one piece at a time into Python.",
}


def _generate_with_heuristic(inp: HintInput, level: int) -> HintResult:
    return HintResult(
        hint_level=level,
        hint_text_md=_FALLBACK_BY_LEVEL[level]
        + "\n\n_(AI hint engine is offline — this is a generic prompt. Real hints tailored to your code will appear once the grader reconnects.)_",
        source="heuristic",
    )


__all__ = ["HintInput", "HintResult", "generate_hint"]
